site_name: Docs Documentation
theme:
  name: material
  custom_dir: overrides
  #favicon: _images/polydocs_Logo.svg
  favicon: _images/polydocs_Icon.svg
  font:
    text: Open Sans
  language: en
  logo: _images/polydocs_Icon.svg
  palette:
      scheme: light
  features:
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+tabs#navigation-tabs
    - navigation.tabs
    - navigation.tabs.sticky
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+tabs#anchor-tracking
    - navigation.tracking
# https://squidfunk.github.io/mkdocs-material/customization/?h=#additional-css
extra_css:
  - _extra/css/extra.css
# https://squidfunk.github.io/mkdocs-material/customization/?h=#additional-javascript
extra_javascript:
  - _extra/javascript/extra.js
extra:
  analytics:
    provider: google
    property: UA-208531131-1
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://docs.google.com/forms/d/e/1FAIpQLScEh_N3lX4JFfvE1fdtImtSv2eVjcEGjlPzsH5usNfN4uNOIg/viewform?usp=pp_url&entry.1764397339=[Feedback]+{title}+-+{url}" target=_blank>feedback form</a>.
markdown_extensions:
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/?h=attr#attribute-lists attr_list is required for several other features. Always enable.
  - attr_list
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/?h=admoni
  - admonition
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#superfences Superfences is required for several other features. Always enable.
  - pymdownx.superfences
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#superfences Used for tags, setting unique templates for certain pages, and other custom frontmatter.
  - meta
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#highlight
  - pymdownx.highlight:
      linenums: true
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#inlinehilite
  - pymdownx.inlinehilite
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#snippets
  - pymdownx.snippets  
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#tabbed
  - pymdownx.tabbed:
      alternate_style: true 
  - tables
  # https://www.mkdocs.org/user-guide/writing-your-docs/#linking-to-pages
  - toc:
      permalink: "#"
plugins:
  - search
  - literate-nav
nav: 
  - DOC²:
    - Overview: doc2/index.md
    - OnBoarding: doc2/onboarding.md
    - Tabel Train: doc2/table-train.md
    - Webhook: doc2/webhook.md
    - ZUGFeRD: doc2/zugpferd-and-peppol.md
  - Workflow:
    - Overview: workflow/index.md
    - Try it out: workflow/quickstart.md
    - Editor UI: workflow/editor-ui.md
    - Understand workflows: 
      - Overview: workflow/workflows/index.md
      - Workflows: workflow/workflows/workflows.md
      - Connections: workflow/workflows/connections.md
      - Nodes: workflow/workflows/nodes.md
      - Notes: workflow/workflows/workflow-notes.md
      - Items: workflow/workflows/items.md
    - Flow logic:
      - Overview: workflow/flow-logic/index.md
      - Merging: workflow/flow-logic/merging.md
      - Looping: workflow/flow-logic/looping.md
      - Error handling: workflow/flow-logic/error-handling.md
    - Mapping and transforming data:
      - Overview: workflow/data/index.md
      - Data structure: workflow/data/data-structure.md
      - Transforming data: workflow/data/transforming-data.md
      - Using code: workflow/data/code.md
    - Code examples: 
      - Overview: workflow/code-examples/index.md
      - Expressions: 
        - Overview: workflow/code-examples/expressions/index.md
        - Methods: workflow/code-examples/expressions/methods.md
        - Variables: workflow/code-examples/expressions/variables.md
        - Data and time with Luxon: workflow/code-examples/expressions/luxon.md
        - JSON with JMESPath: workflow/code-examples/expressions/jmespath.md
      - JavaScript for workflows:
        - Overview: workflow/code-examples/javascript-functions/index.md
        - Methods: workflow/code-examples/javascript-functions/methods.md
        - Variables: workflow/code-examples/javascript-functions/variables.md
        - Get number of items returned by last node: workflow/code-examples/javascript-functions/number-items-last-node.md
        - Check incoming data: workflow/code-examples/javascript-functions/check-incoming-data.md
    - Reference:
      - Overview: workflow/reference/index.md
      - Release notes: workflow/reference/release-notes.md
      - CLI commands: workflow/reference/cli-commands.md
      - Keyboard shortcuts: workflow/reference/keyboard-shortcuts.md
      - Glossary: workflow/reference/glossary.md
      - License: workflow/reference/license.md
      - Data collection: workflow/reference/data-collection.md
    - Integrations: 
      - Overview: workflow/integrations/index.md
      - Core nodes: workflow/integrations/core-nodes/
      - Nodes: workflow/integrations/nodes/
      - Trigger nodes: workflow/integrations/trigger-nodes/
      - Credentials: workflow/integrations/credentials/
      - Creating nodes:
        - Overview: workflow/integrations/creating-nodes/index.md
        - Code-based node building:
          - Overview: workflow/integrations/creating-nodes/code/index.md
          - Standards: workflow/integrations/creating-nodes/code/standards.md
          - Create your first node: workflow/integrations/creating-nodes/code/create-first-node.md
          - Create an n8n-nodes-module: workflow/integrations/creating-nodes/code/create-n8n-nodes-module.md
          - Create a trigger node: workflow/integrations/creating-nodes/code/create-trigger-node.md
          - Use the node developer CLI: workflow/integrations/creating-nodes/code/node-developer-cli.md
          - Node UI elements: workflow/integrations/creating-nodes/code/ui-elements.md
          - HTTP request helpers: workflow/integrations/creating-nodes/code/http-helpers.md
          - Node linter: workflow/integrations/creating-nodes/code/node-linter.md
          - Node review checklist: workflow/integrations/creating-nodes/code/review-checklist.md
          - Troubleshooting: workflow/integrations/creating-nodes/code/troubleshooting-node-development.md
  - FLOW²:
    - Overview: flow2/index.md
  - KV²:
    - Overview: kv2/index.md
  - TE²:
    - Overview: te2/index.md
  - OCR:
    - Overview: ocr/index.md
  - Courses:
    - Overview: courses/index.md
    - Level one:
      - Overview: courses/level-one/index.md
      - Navigating the editor UI: courses/level-one/chapter-1.md
      - Building a mini-workflow: courses/level-one/chapter-2.md
      - Automating a (real-world) use case: courses/level-one/chapter-3.md
      - Designing the workflow: courses/level-one/chapter-4.md
      - Building the workflow:
        - Getting data from the data warehouse: courses/level-one/chapter-5/chapter-5.1.md
        - Inserting data into airtable: courses/level-one/chapter-5/chapter-5.2.md
        - Filtering orders: courses/level-one/chapter-5/chapter-5.3.md
        - Setting values for processing orders: courses/level-one/chapter-5/chapter-5.4.md
        - Calculating booked orders: courses/level-one/chapter-5/chapter-5.5.md
        - Notifying the team: courses/level-one/chapter-5/chapter-5.6.md
        - Scheduling the workflow: courses/level-one/chapter-5/chapter-5.7.md
        - Activating and examining the workflow: courses/level-one/chapter-5/chapter-5.8.md
      - Exporting, importing, and sharing workflows: courses/level-one/chapter-6.md
      - Take the quiz and get your certificate: courses/level-one/chapter-7.md
  # - Hosting n8n: 
  #   - Overview: hosting/index.md
  #   - Installation and hosting options: hosting/options.md
  #   - Installation:
  #     - Overview: hosting/installation/index.md
  #     - Desktop app: hosting/installation/desktop-app.md
  #     - npm: hosting/installation/npm.md
  #     - Docker: hosting/installation/docker.md
  #     - Cloud: hosting/installation/cloud.md
  #   - Configuration: hosting/configuration.md
  #   - User management: hosting/user-management.md
  #   - Environment variables: hosting/environment-variables.md
  #   - Security: hosting/security.md
  #   - Logging: hosting/logging.md
  #   - Server setups:
  #     - Overview: hosting/server-setups/index.md
  #     - Docker Compose: hosting/server-setups/docker-compose.md
  #     - Caddy: hosting/server-setups/caddy.md
  #   - Databases:
  #     - Overview: hosting/databases/index.md
  #     - Supported databases and settings: hosting/databases/supported-databases-settings.md
  #     - Database structure: hosting/databases/structure.md
  #   - Updating:
  #     - Overview: hosting/updating/index.md
  #     - npm: hosting/updating/npm.md
  #     - Docker: hosting/updating/docker.md
  #     - Desktop app: hosting/updating/desktop.md
  #     - Cloud: hosting/updating/cloud.md
  #   - Scaling:
  #     - Overview: hosting/scaling/index.md
  #     - Execution data: hosting/scaling/execution-data.md
  #     - Execution modes and processes: hosting/scaling/execution-modes-processes.md
  #     - Configuring queue mode: hosting/scaling/queue-mode.md
  # - Contributing: contributing.md 