site_name: n8n Documentation
theme:
  name: material
  custom_dir: overrides
  favicon: _images/favicon.ico
  font: false
  language: en
  logo: _images/n8n-docs-icon.svg
  palette:
      scheme: light
  features:
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-annotations
    - content.code.annotate
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+tabs#navigation-tabs
    - navigation.tabs
    - navigation.tabs.sticky
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+tabs#anchor-tracking
    - navigation.tracking
# https://squidfunk.github.io/mkdocs-material/customization/?h=#additional-css
extra_css:
  - _extra/css/extra.css
# https://squidfunk.github.io/mkdocs-material/customization/?h=#additional-javascript
extra_javascript:
  - _extra/javascript/extra.js
markdown_extensions:
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/?h=attr#attribute-lists attr_list is required for several other features. Always enable.
  - attr_list
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/?h=admoni
  - admonition
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#superfences Superfences is required for several other features. Always enable.
  - pymdownx.superfences
  # https://squidfunk.github.io/mkdocs-material/reference/images/
  - md_in_html
  - pymdownx.details
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#superfences Used for tags, setting unique templates for certain pages, and other custom frontmatter.
  - meta
  - pymdownx.details
  # https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#highlight
  - pymdownx.highlight:
      linenums: true
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#superfences Superfences is required for several other features. Always enable.
  - pymdownx.superfences:
      # https://squidfunk.github.io/mkdocs-material/reference/diagrams/
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
      # https://facelessuser.github.io/pymdown-extensions/extensions/superfences/#preserve-tabs
      preserve_tabs: true
  - pymdownx.tasklist:
      custom_checkbox: true
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#inlinehilite
  - pymdownx.inlinehilite
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#snippets
  - pymdownx.snippets
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#tabbed
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  # https://www.mkdocs.org/user-guide/writing-your-docs/#linking-to-pages
  - toc:
      permalink: "#"
plugins:
  - search
  # https://github.com/oprypin/mkdocs-literate-nav
  - literate-nav
nav:
  - Using n8n:
    - Welcome: index.md
    - Try it out: 
      - Overview: try-it-out/index.md
      - A very quick quickstart: try-it-out/quickstart.md
      - A longer introduction: try-it-out/longer-introduction.md
    - Editor UI: editor-ui.md
    - Understand workflows:
      - Overview: workflows/index.md
      - Workflows: workflows/workflows.md
      - Connections: workflows/connections.md
      - Nodes: workflows/nodes.md
      - Items: workflows/items.md
      - Sticky Notes: workflows/sticky-notes.md
    - Flow logic:
      - Overview: flow-logic/index.md
      - Merging: flow-logic/merging.md
      - Looping: flow-logic/looping.md
      - Error handling: flow-logic/error-handling.md
    - Data:
      - Overview: data/index.md
      - Data structure: data/data-structure.md
      - Transforming data: data/transforming-data.md
      - Process data using code: data/code.md
      - Data mapping: data/data-mapping.md
      - Data pinning: data/data-pinning.md
      - Data editing: data/data-editing.md
      - Data item linking: 
        - Overview: data/data-item-linking/index.md
        - Item linking scenarios: data/data-item-linking/item-linking-scenarios.md
        - Item linking errors: data/data-item-linking/item-linking-errors.md
    - Expressions and JavaScript:
      - Overview: code-examples/index.md
      - Built-in methods and variables: code-examples/methods-variables.md
      - Expressions examples:
        - Overview: code-examples/expressions/index.md
        - Methods and variables:
          - Overview: code-examples/expressions/methods-variables/index.md
          - execution: code-examples/expressions/methods-variables/execution.md
          - workflow: code-examples/expressions/methods-variables/workflow.md
        - Date and time with Luxon: code-examples/expressions/luxon.md
        - JSON with JMESPath: code-examples/expressions/jmespath.md
      - JavaScript examples:
        - Overview: code-examples/javascript-functions/index.md
        - Methods and variables:
          - Overview: code-examples/javascript-functions/methods-variables/index.md
          - evaluateExpression: code-examples/javascript-functions/methods-variables/evaluate-expression.md
          - node: code-examples/javascript-functions/methods-variables/node.md
          - (node-name).all: code-examples/javascript-functions/methods-variables/all.md
          - (node-name).itemAt: code-examples/javascript-functions/methods-variables/item-at.md
          - execution: code-examples/javascript-functions/methods-variables/execution.md
          - runIndex: code-examples/javascript-functions/methods-variables/run-index.md
          - workflow: code-examples/javascript-functions/methods-variables/workflow.md
        - Date and time with Luxon: code-examples/javascript-functions/luxon.md
        - JSON with JMESPath: code-examples/javascript-functions/jmespath.md
        - Get number of items returned by last node: code-examples/javascript-functions/number-items-last-node.md
        - Split binary file data into individual items: code-examples/javascript-functions/split-binary-file-data.md
        - Get the binary data buffer: code-examples/javascript-functions/get-binary-data-buffer.md
        - Check incoming data: code-examples/javascript-functions/check-incoming-data.md
    - Reference:
      - Overview: reference/index.md
      - Release notes: reference/release-notes.md
      - CLI commands: reference/cli-commands.md
      - Keyboard shortcuts: reference/keyboard-shortcuts.md
      - Glossary: reference/glossary.md
      - License: reference/license.md
      - Data collection: reference/data-collection.md
  - Integrations:
    - Overview: integrations/index.md
    - Built-in nodes:
      - Overview: integrations/builtin/index.md
      - Core nodes: integrations/builtin/core-nodes/
      - App nodes: integrations/builtin/app-nodes/
      - Trigger nodes: integrations/builtin/trigger-nodes/
      - Credentials: integrations/builtin/credentials/
    - Custom API actions for existing nodes: integrations/custom-operations.md
    - Community nodes:
      - Overview: integrations/community-nodes/index.md
      - Installation and management: integrations/community-nodes/installation.md
      - Risks: integrations/community-nodes/risks.md
      - Blocklist: integrations/community-nodes/blocklist.md
      - Using community nodes: integrations/community-nodes/usage.md
      - Troubleshooting: integrations/community-nodes/troubleshooting.md
      - Building community nodes: integrations/community-nodes/build-community-nodes.md
    - Creating nodes:
      - Overview: integrations/creating-nodes/index.md
      - Plan your node:
        - Overview: integrations/creating-nodes/plan/index.md
        - Choose a node building style: integrations/creating-nodes/plan/choose-node-method.md
        - Node UI design: integrations/creating-nodes/plan/node-ui-design.md
        - Choose node file structure: integrations/creating-nodes/build/reference/node-file-structure.md
      - Build your node:
        - Overview: integrations/creating-nodes/build/index.md       
        - Set up your development environment: integrations/creating-nodes/build/node-development-environment.md
        - "Tutorial: Build a declarative-style node": integrations/creating-nodes/build/declarative-style-node.md
        - Reference:
          - Overview: integrations/creating-nodes/build/reference/index.md
          - Node UI elements: integrations/creating-nodes/build/reference/ui-elements.md 
          - Code standards: integrations/creating-nodes/build/reference/code-standards.md
          - Versioning: integrations/creating-nodes/build/reference/node-versioning.md 
          - File structure: integrations/creating-nodes/build/reference/node-file-structure.md
          - Base files: integrations/creating-nodes/build/reference/node-base-files.md
          - Codex files: integrations/creating-nodes/build/reference/node-codex-files.md  
          - Credentials files: integrations/creating-nodes/build/reference/credentials-files.md    
          - HTTP request helpers: integrations/creating-nodes/build/reference/http-helpers.md
          - Paired items: integrations/creating-nodes/build/reference/paired-items.md
      - Test your node:
        - Overview: integrations/creating-nodes/test/index.md
        - Run your node locally: integrations/creating-nodes/test/run-node-locally.md
        - Node linter: integrations/creating-nodes/test/node-linter.md
        - Troubleshooting: integrations/creating-nodes/test/troubleshooting-node-development.md
      - Deploy your node:
        - Overview: integrations/creating-nodes/deploy/index.md
        - Submit community nodes: integrations/creating-nodes/deploy/submit-community-nodes.md
        - Install private nodes: integrations/creating-nodes/deploy/install-private-nodes.md
  - Hosting n8n:
    - Overview: hosting/index.md
    - Installation and hosting options: hosting/options.md
    - Installation:
      - Overview: hosting/installation/index.md
      - Desktop app: hosting/installation/desktop-app.md
      - npm: hosting/installation/npm.md
      - Docker: hosting/installation/docker.md
      - Cloud: hosting/installation/cloud.md
    - Configuration: hosting/configuration.md    
    - Environment variables: hosting/environment-variables.md
    - User management: hosting/user-management.md
    - Security: hosting/security.md
    - Logging: hosting/logging.md
    - Server setups:
      - Overview: hosting/server-setups/index.md
      - Docker Compose: hosting/server-setups/docker-compose.md
      - Caddy: hosting/server-setups/caddy.md
      - Digital Ocean: hosting/server-setups/digital-ocean.md
    - Databases:
      - Overview: hosting/databases/index.md
      - Supported databases and settings: hosting/databases/supported-databases-settings.md
      - Database structure: hosting/databases/structure.md
    - Updating:
      - Overview: hosting/updating/index.md
      - npm: hosting/updating/npm.md
      - Docker: hosting/updating/docker.md
      - Desktop app: hosting/updating/desktop.md
      - Cloud: hosting/updating/cloud.md
    - Scaling:
      - Overview: hosting/scaling/index.md
      - Execution data: hosting/scaling/execution-data.md
      - Execution modes and processes: hosting/scaling/execution-modes-processes.md
      - Configuring queue mode: hosting/scaling/queue-mode.md
  - API:
    - The n8n public API: api/index.md
    - Authentication: api/authentication.md
    - Pagination: api/pagination.md
    - Using the API playground: api/using-api-playground.md
    - API reference: api/api-reference.md
  - Embed:
    - n8n Embed: embed/index.md
    - Prerequisites: embed/prerequisites.md
    - Deployment: embed/deployment.md
    - Configuration: embed/configuration.md
    - Workflow management: embed/managing-workflows.md
    - Workflows templates: embed/workflow-templates.md
  - Courses:
      - Overview: courses/index.md
      - Level one:
        - Overview: courses/level-one/index.md
        - Navigating the editor UI: courses/level-one/chapter-1.md
        - Building a mini-workflow: courses/level-one/chapter-2.md
        - Automating a (real-world) use case: courses/level-one/chapter-3.md
        - Designing the workflow: courses/level-one/chapter-4.md
        - Building the workflow:
          - Getting data from the data warehouse: courses/level-one/chapter-5/chapter-5.1.md
          - Inserting data into airtable: courses/level-one/chapter-5/chapter-5.2.md
          - Filtering orders: courses/level-one/chapter-5/chapter-5.3.md
          - Setting values for processing orders: courses/level-one/chapter-5/chapter-5.4.md
          - Calculating booked orders: courses/level-one/chapter-5/chapter-5.5.md
          - Notifying the team: courses/level-one/chapter-5/chapter-5.6.md
          - Scheduling the workflow: courses/level-one/chapter-5/chapter-5.7.md
          - Activating and examining the workflow: courses/level-one/chapter-5/chapter-5.8.md
        - Exporting and importing workflows: courses/level-one/chapter-6.md
        - Test your knowledge: courses/level-one/chapter-7.md
      - Level two:
        - Overview: courses/level-two/index.md
        - Understanding the data structure: courses/level-two/chapter-1.md
        - Processing different data types: courses/level-two/chapter-2.md
        - Merging and splitting data: courses/level-two/chapter-3.md
        - Dealing with errors in workflows: courses/level-two/chapter-4.md
        - Automating a business workflow:
          - Use case: courses/level-two/chapter-5/chapter-5.0.md
          - Workflow 1: courses/level-two/chapter-5/chapter-5.1.md
          - Workflow 2: courses/level-two/chapter-5/chapter-5.2.md
          - Workflow 3: courses/level-two/chapter-5/chapter-5.3.md
        - Test your knowledge: courses/level-two/chapter-6.md
  - Contributing: contributing.md
