name: ci 
on:
  push:
    branches:
      - master 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material 
      - run: pip install -r requirements.txt
      #- run: pip install git+https://${{ secrets.GH_TOKEN }}@github.com/squidfunk/mkdocs-material-insiders.git
      #- run: mkdocs build
      - run: mkdocs gh-deploy --force
      # - name: Pushes to another repository
      #   id: push_directory
      #   uses: cpina/github-action-push-to-another-repository@devel
      #   env:
      #     API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      #   with:
      #     source-directory: site/
      #     destination-github-username: 'Fellow-Consulting-AG'
      #     destination-repository-name: 'doc-site'
      #     user-email: daniel.jordan@fellow-consulting.de
      #     commit-message: See ORIGIN_COMMIT from $GITHUB_REF
      #     target-branch: main


